### PR TITLE
Splits parking-lots.geojson into individaul city files

### PR DESCRIPTION
**Pull request by tunglinn**
Next step is to get the map to render using the split files.

### CODE REVIEW

**Comment by tunglinn** [comment]
When do we remove the original parking-lots.geojson file?

**Comment by Eric-Arellano** [comment]
Wait this was merged without code review?

**Comment by tunglinn** [comment]
> Wait this was merged without code review?

My bad! I saw the green button and just clicked it. I'll add edits to another PR.

**Comment by Eric-Arellano** [comment]
Oh, you merged into your lazy-loading feature branch. So no worries! We still have branch protection on `main`.

**Pull request merged**
